name: Workflow COmmands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing Semicolon"
            - name: Setting error message with params
              run: echo "::error title=Error,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting debug message with params
              run: echo "::debug title=Debug,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting warning message with params
              run: echo "::warning title=Warning,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting notice message with params
              run: echo "::notice title=Notice,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Group of logs
              run: |
                echo "::group::My group title"
                echo "Inide group"
                echo "::endgroup::"
            - name: Masking a value
              run: echo "::add-mask::Secret String"
            - name: Echo a secret
              run: Echo "Secret String"  